### ISSUE TITLE
Warning on game startup with a procam2d

### ISSUE THREAD

**Issue by jodle001** [daz-b-like/ProCam2D_Godot4.x#7]
**Describe the bug**
When a scene is loaded with a ProCam2D, if 2d physics interpolation is turned on you will get a warning in the Debugger log:

W 0:00:00:0636   _update_process_callback: Camera2D overridden to physics process mode due to use of physics interpolation.
  <C++ Source>   scene/2d/camera_2d.cpp:92 @ _update_process_callback()

**To Reproduce**
1. Turn on 2d physics interpolation.
2. Put ProCam2D into scene. 
3. Make sure to set ProCam2D Process Frame setting to physics.
4. Run that scene.
5. The Warning should pop up.

**Expected behavior**
Seems like as long as the Process Frame is selected physics this warning shouldn't occur.

**Screenshots**
![image](https://github.com/user-attachments/assets/a4b9994d-f111-4b9c-84d0-128b1b082ee2)

**Desktop (please complete the following information):**
 - OS: Windows and macOS,
 - Godot Version 4.3 stable
 - Plugin Version 1.0

**Comment by daz-b-like** [comment]
The warning is actually inevitable. Even having a single camera2D produces the warning if physics interplation is on.

**Comment by klootas** [comment]
Just so I understand, is it by design that we can't silence this warning? So any game using physics interpolation will always warn about the camera no matter how you configure the camera?
Nothing I tried could silence this warning (and I don't know of a way to tap into the log stream in C# to manually filter it out).

Thanks
